[package]
name = "fluxdown-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
tauri-build.workspace = true

[dependencies]
anyhow.workspace = true
fluxdown-core = { path = "../../../crates/fluxdown-core" }
open.workspace = true
reqwest.workspace = true
tauri-plugin-clipboard-manager.workspace = true
tauri-plugin-dialog.workspace = true
tauri-plugin-notification.workspace = true
tauri-plugin-single-instance.workspace = true
tauri-plugin-window-state.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri.workspace = true
tokio.workspace = true
url.workspace = true

[dev-dependencies]
tempfile.workspace = true
